# Generated by Django 4.0.1 on 2022-01-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_frienrrequests_user_frienrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='frienRequests',
            new_name='friendRequests',
        ),
    ]
