# Generated by Django 4.0.1 on 2022-01-24 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_room_online_room_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.AddField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
