# Generated by Django 4.0.1 on 2022-01-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_room_online_room_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='online',
            new_name='members',
        ),
    ]
